title: "KTU S3 AI & Data Science (GNEST305)"
description: "Structured slides, labs, and resources for KTU S3 Introduction to Artificial Intelligence & Data Science."
url: "https://shailooz.github.io/GNEST305"
baseurl: ""

remote_theme: pages-themes/hacker@v0.2.0

repository: shailooz/GNEST305
logo: "/assets/logo.png"
favicon: "/assets/favicon.ico"

author:
  name: "Dr. Shailesh Sivan"
  email: "shaileshsivan@gmail.com"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: ""

social_links:
  github: https://github.com/shailooz/GNEST305/new/master
  email: shaileshsivan@gmail.com

footer_content: "Maintained for KTU S3 AI & Data Science learners. Share and learn collaboratively."
