title: "KTU S3 AI & Data Science (GNEST305)"
description: "Structured slides, labs, and resources for KTU S3 Introduction to Artificial Intelligence & Data Science."
url: "https://shailooz.github.io/GNEST305"
baseurl: "" # leave empty if deploying at root

remote_theme: pages-themes/slate@v0.2.0

repository: shailooz/GNEST305

logo: "/assets/logo.png" # add your logo if desired

author:
  name: "Dr. Shailesh Sivan"
  email: "shaileshsivan@gmail.com"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

google_analytics: "" # add tracking ID if needed

# Footer settings
footer_content: "Maintained for KTU S3 AI & Data Science learners. Share and learn collaboratively."

# Optional navigation links (enable when you add pages)
# header_pages:
#   - index.md
#   - about.md
#   - contact.md
